[package]
name = "sorter"
version = "0.1.0"
edition = "2024"

[dependencies]
bytemuck = "1.25.0"
futures-intrusive = "0.5.0"
pollster = "0.4.0"
rand = "0.8"
rayon = "1.7"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
wgpu = "27.0.1"
